### ISSUE TITLE
Documentation clarification on Typescript version

### ISSUE THREAD

**Issue by BL-marcusrogers** [aparajita/capacitor-logger#1]
Fantastic plug-in! Might want to add in the documentation that Typescript must be 4.5.x or greater (otherwise you get build errors complaining that `type` is not exported from ./definitions). Once I updated Typescript everything just worked out of the box. Very nice!

**Comment by aparajita** [comment]
Thanks for finding that, I will add it when I get a chance. Happy to know that someone out there is actually using it!
